import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'SizeFashion',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
        <title>SizeFashion</title>
        <link rel="icon" href="./favicon.ico" />
      </Head>

      <body className={inter.className}
        style={{
          height: '100%',
          width: '100%',
          backgroundColor: 'white'
        }}
      >{children}</body>
    </html>
  )
}
